[tool.poetry]
name = "python-sdk"
version = "0.1.0"
description = ""
authors = ["David Riccitelli <david@wordlift.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
gql = "^3.5.0"
tenacity = "^9.0.0"
aiohttp = "^3.10.5"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
pytest-asyncio = "^0.24.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
