"""Graph audit module: KPI extraction from RDF graph files."""

from __future__ import annotations

from ._auditor import AuditOptions, GraphAuditor
from ._loader import LoadError, LoadResult, load_graph
from ._profile import shape_specs_for_profile
from ._report import GraphAuditReport
from .kpis import (
    BrokenLinksKpi,
    BrokenLinksResult,
    DuplicatesKpi,
    DuplicatesResult,
    EdgeNodeRatioKpi,
    EdgeNodeRatioResult,
    EdgesKpi,
    EdgesResult,
    EntityTypesKpi,
    EntityTypesResult,
    IsolatedGraphsKpi,
    IsolatedGraphsResult,
    IssueEntry,
    MerchantResult,
    OrphansKpi,
    OrphansResult,
    PropertiesKpi,
    PropertiesResult,
    RichSnippetsKpi,
    RichSnippetsResult,
    SchemaComplianceKpi,
    SchemaComplianceResult,
    TotalsKpi,
    TotalsResult,
    UniqueUrlsKpi,
    UniqueUrlsResult,
    UrlComplianceResult,
)

__all__ = [
    "AuditOptions",
    "BrokenLinksKpi",
    "BrokenLinksResult",
    "DuplicatesKpi",
    "DuplicatesResult",
    "EdgeNodeRatioKpi",
    "EdgeNodeRatioResult",
    "EdgesKpi",
    "EdgesResult",
    "EntityTypesKpi",
    "EntityTypesResult",
    "GraphAuditReport",
    "GraphAuditor",
    "IsolatedGraphsKpi",
    "IsolatedGraphsResult",
    "IssueEntry",
    "LoadError",
    "LoadResult",
    "MerchantResult",
    "OrphansKpi",
    "OrphansResult",
    "PropertiesKpi",
    "PropertiesResult",
    "RichSnippetsKpi",
    "RichSnippetsResult",
    "SchemaComplianceKpi",
    "SchemaComplianceResult",
    "TotalsKpi",
    "TotalsResult",
    "UniqueUrlsKpi",
    "UniqueUrlsResult",
    "UrlComplianceResult",
    "load_graph",
    "shape_specs_for_profile",
]
